#!/usr/bin/with-contenv bashio
# Printernizer - Home Assistant Add-on Startup Script
# Handles configuration from Home Assistant and starts the application

set -e

# Colors for output
bashio::log.info "Starting Printernizer Home Assistant Add-on v2.0.20..."

# Read configuration from Home Assistant options
CONFIG_PATH="/data/options.json"

# Parse options with jq and bashio
LOG_LEVEL=$(bashio::config 'log_level' 'info')
TIMEZONE=$(bashio::config 'timezone' 'Europe/Berlin')
LIBRARY_FOLDER=$(bashio::config 'library_folder' '/data/printernizer/library')
ENABLE_3D_PREVIEW=$(bashio::config 'enable_3d_preview' 'true')
ENABLE_WEBSOCKETS=$(bashio::config 'enable_websockets' 'true')
ENABLE_BUSINESS_REPORTS=$(bashio::config 'enable_business_reports' 'true')
TIMELAPSE_ENABLED=$(bashio::config 'timelapse_enabled' 'true')
TIMELAPSE_SOURCE_FOLDER=$(bashio::config 'timelapse_source_folder' '/data/timelapse-images')
TIMELAPSE_OUTPUT_FOLDER=$(bashio::config 'timelapse_output_folder' '/data/timelapses')
TIMELAPSE_OUTPUT_STRATEGY=$(bashio::config 'timelapse_output_strategy' 'separate')
TIMELAPSE_AUTO_PROCESS_TIMEOUT=$(bashio::config 'timelapse_auto_process_timeout' '300')
TIMELAPSE_CLEANUP_AGE_DAYS=$(bashio::config 'timelapse_cleanup_age_days' '30')

bashio::log.info "Configuration loaded from Home Assistant"
bashio::log.info "  • Log Level: ${LOG_LEVEL}"
bashio::log.info "  • Timezone: ${TIMEZONE}"
bashio::log.info "  • Library Folder: ${LIBRARY_FOLDER}"
bashio::log.info "  • 3D Preview: ${ENABLE_3D_PREVIEW}"
bashio::log.info "  • WebSockets: ${ENABLE_WEBSOCKETS}"
bashio::log.info "  • Business Reports: ${ENABLE_BUSINESS_REPORTS}"
bashio::log.info "  • Timelapse Enabled: ${TIMELAPSE_ENABLED}"
bashio::log.info "  • Timelapse Source: ${TIMELAPSE_SOURCE_FOLDER}"
bashio::log.info "  • Timelapse Output: ${TIMELAPSE_OUTPUT_FOLDER}"
bashio::log.info "  • Printer Config: /data/printernizer/printers.json (persistent)"

# Set timezone
export TZ="${TIMEZONE}"
bashio::log.info "Timezone set to ${TZ}"

# Create necessary directories
bashio::log.info "Setting up directories..."
mkdir -p /data/printernizer
mkdir -p "${LIBRARY_FOLDER}"
mkdir -p /data/printernizer/printer-files
mkdir -p /data/printernizer/preview-cache
mkdir -p /data/printernizer/backups
mkdir -p "${TIMELAPSE_SOURCE_FOLDER}"
mkdir -p "${TIMELAPSE_OUTPUT_FOLDER}"
mkdir -p /app/logs
mkdir -p /app/temp

# Fix permissions for /data directory to allow config file writes
# This prevents "[Errno 1] Operation not permitted" when saving printer config
if [ -d "/data/printernizer" ]; then
    bashio::log.info "Ensuring write permissions for config files..."
    chmod -R 777 /data/printernizer 2>/dev/null || true
fi

# Generate environment configuration
bashio::log.info "Generating application configuration..."
cat > /app/.env << EOF
# Generated by Home Assistant Add-on
ENVIRONMENT=production
DEPLOYMENT_MODE=homeassistant
HA_INGRESS=true

# Server configuration
HOST=0.0.0.0
PORT=8000

# Logging
LOG_LEVEL=${LOG_LEVEL}

# Timezone and locale
TIMEZONE=${TIMEZONE}
TZ=${TIMEZONE}

# Database
DATABASE_PATH=/data/printernizer/printernizer.db

# Printer configuration (persistent storage in /data)
PRINTER_CONFIG_PATH=/data/printernizer/printers.json

# File paths (persistent storage in /data)
LIBRARY_PATH=${LIBRARY_FOLDER}
DOWNLOADS_PATH=/data/printernizer/printer-files
UPLOAD_PATH=/data/printernizer/printer-files
BACKUP_PATH=/data/printernizer/backups
CACHE_PATH=/data/printernizer/preview-cache

# CORS - Allow Ingress
CORS_ORIGINS=http://172.30.32.2,https://172.30.32.2

# Feature flags from HA configuration
ENABLE_3D_PREVIEW=${ENABLE_3D_PREVIEW}
ENABLE_WEBSOCKETS=${ENABLE_WEBSOCKETS}
ENABLE_BUSINESS_REPORTS=${ENABLE_BUSINESS_REPORTS}

# Timelapse configuration
TIMELAPSE_ENABLED=${TIMELAPSE_ENABLED}
TIMELAPSE_SOURCE_FOLDER=${TIMELAPSE_SOURCE_FOLDER}
TIMELAPSE_OUTPUT_FOLDER=${TIMELAPSE_OUTPUT_FOLDER}
TIMELAPSE_OUTPUT_STRATEGY=${TIMELAPSE_OUTPUT_STRATEGY}
TIMELAPSE_AUTO_PROCESS_TIMEOUT=${TIMELAPSE_AUTO_PROCESS_TIMEOUT}
TIMELAPSE_CLEANUP_AGE_DAYS=${TIMELAPSE_CLEANUP_AGE_DAYS}
TIMELAPSE_FLICKERFREE_PATH=/usr/local/bin/do_timelapse.sh

# Printer settings
PRINTER_POLLING_INTERVAL=30
MAX_CONCURRENT_DOWNLOADS=5

# German business defaults
CURRENCY=EUR
VAT_RATE=0.19
BUSINESS_LOCATION=Home

# Security for Ingress
INGRESS_SECURITY=true
ALLOWED_IPS=172.30.32.2
EOF

bashio::log.info "Environment configuration created"

# Database initialization is handled by the Python application
# The application will create tables and run migrations automatically
bashio::log.info "Database will be initialized by application on startup"

# Parse and log printer configuration
PRINTER_COUNT=$(bashio::config 'printers | length' '0')
if [ "$PRINTER_COUNT" -gt 0 ]; then
    bashio::log.info "Found ${PRINTER_COUNT} printer(s) in configuration:"
    for i in $(seq 0 $((PRINTER_COUNT - 1))); do
        PRINTER_NAME=$(bashio::config "printers[${i}].name")
        PRINTER_TYPE=$(bashio::config "printers[${i}].type")
        PRINTER_IP=$(bashio::config "printers[${i}].ip_address")
        PRINTER_ENABLED=$(bashio::config "printers[${i}].enabled" "true")

        bashio::log.info "  • ${PRINTER_NAME} (${PRINTER_TYPE}) @ ${PRINTER_IP} - Enabled: ${PRINTER_ENABLED}"

        # Create printer ID from name (convert to lowercase, replace spaces with underscores)
        PRINTER_ID=$(echo "$PRINTER_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd '[:alnum:]_')

        # Export printer configuration to environment variables for application
        export PRINTERNIZER_PRINTER_${PRINTER_ID}_NAME="$PRINTER_NAME"
        export PRINTERNIZER_PRINTER_${PRINTER_ID}_TYPE="$PRINTER_TYPE"
        export PRINTERNIZER_PRINTER_${PRINTER_ID}_IP_ADDRESS="$PRINTER_IP"
        export PRINTERNIZER_PRINTER_${PRINTER_ID}_IS_ACTIVE="$PRINTER_ENABLED"

        # Type-specific credentials
        if [ "$PRINTER_TYPE" = "bambu_lab" ]; then
            ACCESS_CODE=$(bashio::config "printers[${i}].access_code" "")
            SERIAL_NUMBER=$(bashio::config "printers[${i}].serial_number" "")

            if [ -n "$ACCESS_CODE" ]; then
                export PRINTERNIZER_PRINTER_${PRINTER_ID}_ACCESS_CODE="$ACCESS_CODE"
            fi

            if [ -n "$SERIAL_NUMBER" ]; then
                export PRINTERNIZER_PRINTER_${PRINTER_ID}_SERIAL_NUMBER="$SERIAL_NUMBER"
            fi
        elif [ "$PRINTER_TYPE" = "prusa" ]; then
            API_KEY=$(bashio::config "printers[${i}].api_key" "")

            if [ -n "$API_KEY" ]; then
                export PRINTERNIZER_PRINTER_${PRINTER_ID}_API_KEY="$API_KEY"
            fi
        fi

        bashio::log.info "  ✓ Exported printer configuration to environment: PRINTERNIZER_PRINTER_${PRINTER_ID}_*"
    done
else
    bashio::log.warning "No printers configured. Add printers via the web interface."
fi

# Network connectivity check
bashio::log.info "Checking network connectivity..."
if ping -c 1 -W 2 8.8.8.8 &> /dev/null; then
    bashio::log.info "Network connectivity: OK"
else
    bashio::log.warning "Limited network connectivity - printer connections may fail"
fi

# Display startup information
bashio::log.info "======================================"
bashio::log.info "Printernizer Add-on Configuration Complete"
bashio::log.info "======================================"
bashio::log.info "Access via Home Assistant Ingress or:"
bashio::log.info "  Web Interface: http://[host]:8000"
bashio::log.info "  API Docs: http://[host]:8000/docs"
bashio::log.info "======================================"

# Start the application
bashio::log.info "Starting Printernizer application server..."
bashio::log.info "This may take a moment while services initialize..."
cd /app
exec python3 src/main.py
